import { useEffect, useState } from "react";
import axios from "axios";
import { BrowserRouter, NavLink, Routes, Route, useNavigate, useParams } from "react-router-dom";
import { AreaChart, Area, ResponsiveContainer, XAxis, YAxis, Tooltip, BarChart, Bar } from "recharts";
import { Activity, ArrowUpRight, BarChart3, ChevronRight, CircleHelp, Database, Gauge, Layers3, RefreshCw, ShieldCheck, Target, TrendingUp } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const fmt = (value) => new Date(value).toLocaleString([], { weekday: "short", hour: "2-digit", minute: "2-digit" });
const nav = [{to:"/", label:"Fixtures", icon:Activity}, {to:"/portfolio", label:"Portfolios", icon:Layers3}, {to:"/history", label:"Performance", icon:BarChart3}, {to:"/model", label:"Model insight", icon:Target}];

function Shell({children}) { return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">CE</span><span>Cric<span>Edge</span><small>ANALYTICS ENGINE</small></span></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(({to,label,icon:Icon})=><NavLink data-testid={`nav-${label.toLowerCase().replace(' ','-')}`} key={to} to={to} end={to==="/"}><Icon size={17}/>{label}<ChevronRight className="nav-arrow" size={14}/></NavLink>)}</nav><div className="side-status"><div className="live-dot"/> DATA PIPELINE <strong>OPERATIONAL</strong><p>Last normalized<br/><b>2 min ago</b></p></div><div className="side-footer"><ShieldCheck size={15}/> Read-only environment<br/><span>v0.8.2 · UTC</span></div></aside><main><header className="topbar"><div className="crumb"><span>CRICEDGE</span><ChevronRight size={14}/><b>ANALYTICS</b></div><div className="top-actions"><span className="sync"><span className="live-dot"/> LIVE FEED</span><button data-testid="help-button" className="icon-btn" title="Help"><CircleHelp size={18}/></button><div className="avatar">CE</div></div></header>{children}</main></div> }

function Metric({label,value,delta,icon:Icon}) { return <div className="metric" data-testid={`metric-${label.toLowerCase().replaceAll(' ','-')}`}><div className="metric-top"><span>{label}</span><Icon size={16}/></div><b>{value}</b><small className={delta?.startsWith("+")?"up":""}>{delta}</small></div> }
function FixtureCard({fixture}) { const navigate=useNavigate(); return <button className="fixture-card" data-testid={`fixture-card-${fixture.id}`} onClick={()=>navigate(`/fixture/${fixture.id}`)}><div className="card-head"><div><span className="eyebrow">{fixture.competition} · {fixture.format}</span><h3>{fixture.teams[0]} <i>vs</i> {fixture.teams[1]}</h3></div><span className={`tag ${fixture.model_tag === "HIGH SIGNAL" ? "red" : fixture.model_tag === "BALANCED" ? "amber" : "blue"}`}>{fixture.model_tag}</span></div><div className="fixture-meta"><span>{fmt(fixture.start_time)}</span><span>{fixture.venue}</span><span className="confidence"><Gauge size={13}/> {fixture.confidence}% confidence</span></div><div className="odds-row">{fixture.odds.map((odd)=><div className="odd" key={odd.name}><span>{odd.name}</span><b>{odd.price.toFixed(2)}</b><small>{Math.round(odd.probability*100)}% model</small></div>)}<div className="open-detail">OPEN <ArrowUpRight size={15}/></div></div></button> }
function FormatFilter({formats,active,onChange,total}) {
  const chips = [{key:"ALL", label:"All formats", count: total, profile:"Full cricket slate"}, ...formats.map(f=>({key:f.key, label:f.label, count:f.count, profile:f.profile}))];
  return <div className="format-filter" data-testid="format-filter">
    <div className="filter-label"><span className="eyebrow">FORMAT STRATEGY</span><small>Predictions adapt to each format</small></div>
    <div className="chip-row">{chips.map(c=><button key={c.key} data-testid={`format-chip-${c.key.toLowerCase()}`} className={`chip ${active===c.key?"active":""} ${c.count===0&&c.key!=="ALL"?"empty":""}`} onClick={()=>onChange(c.key)} disabled={c.count===0&&c.key!=="ALL"} title={c.profile}><span>{c.label}</span><b>{c.count}</b></button>)}</div>
  </div>
}
function Overview() {
  const [fixtures,setFixtures]=useState([]);
  const [formats,setFormats]=useState([]);
  const [total,setTotal]=useState(0);
  const [active,setActive]=useState("ALL");
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  useEffect(()=>{
    axios.get(`${API}/fixtures/formats`).then(r=>{setFormats(r.data.formats);setTotal(r.data.total)}).catch(()=>{});
  },[]);
  useEffect(()=>{
    setLoading(true); setError("");
    const params = active==="ALL" ? {} : {params:{format:active}};
    axios.get(`${API}/fixtures`, params).then(r=>setFixtures(r.data)).catch(()=>setError("Fixture feed unavailable")).finally(()=>setLoading(false));
  },[active]);
  return <Shell><div className="page"><div className="page-intro"><div><div className="eyebrow accent">MATCH CENTER / 06:42 UTC</div><h1>Fixture explorer</h1><p>Signals, prices, and context for the global cricket slate.</p></div><button data-testid="refresh-fixtures-button" className="outline-btn" onClick={()=>window.location.reload()}><RefreshCw size={15}/> REFRESH FEED</button></div><div className="disclaimer" data-testid="analytics-disclaimer"><ShieldCheck size={17}/><span><b>ANALYTICAL SIGNALS ONLY</b> CricEdge publishes model outputs for research and education. This is not wagering advice and contains no stake sizing.</span></div><div className="metrics"><Metric label="Upcoming fixtures" value={total||"—"} delta="Live provider feed" icon={Activity}/><Metric label="Model coverage" value="92.6%" delta="+1.4% this week" icon={Database}/><Metric label="Mean confidence" value="68.4%" delta="+3.2% vs baseline" icon={TrendingUp}/><Metric label="Pipeline status" value="NOMINAL" delta="Updated 2m ago" icon={Gauge}/></div>
    <FormatFilter formats={formats} active={active} total={total} onChange={setActive}/>
    <div className="section-heading"><div><span className="eyebrow">UPCOMING SLATE · {active==="ALL"?"ALL FORMATS":active.toUpperCase()}</span><h2>Next fixtures</h2></div><span className="count" data-testid="fixture-count">{loading?"—":`${fixtures.length} LOADED`}</span></div>{error&&<div className="error" data-testid="fixture-error">{error}</div>}<div className="fixture-list">{loading ? <div className="loading" data-testid="fixtures-loading">Loading normalized fixtures…</div> : fixtures.length===0 ? <div className="loading" data-testid="fixtures-empty">No fixtures for this format right now.</div> : fixtures.map(f=><FixtureCard fixture={f} key={f.id}/>)}</div><div className="lower-grid"><div className="callout"><div className="callout-icon"><Database size={19}/></div><div><b>Source health</b><p>Cricsheet history normalized · bookmaker adapter ready</p></div><span className="healthy">● HEALTHY</span></div><div className="callout"><div className="callout-icon blue-icon"><Target size={19}/></div><div><b>Model registry</b><p>Ensemble v0.8.2 · retrained 14 Jun 2025</p></div><NavLink to="/model" data-testid="view-model-link">VIEW MODEL <ArrowUpRight size={14}/></NavLink></div></div></div></Shell>
}
function Detail() { const {id}=useParams(); const [data,setData]=useState(null); useEffect(()=>{axios.get(`${API}/fixtures/${id}/predictions`).then(r=>setData(r.data))},[id]); if(!data)return <Shell><div className="loading">Loading model detail…</div></Shell>; return <Shell><div className="page"><NavLink className="back" to="/" data-testid="back-fixtures-link">← ALL FIXTURES</NavLink><div className="page-intro"><div><div className="eyebrow accent">FIXTURE DETAIL / {data.fixture.format}</div><h1>{data.fixture.teams[0]} <em>vs</em> {data.fixture.teams[1]}</h1><p>{data.fixture.competition} · {data.fixture.venue} · {fmt(data.fixture.start_time)}</p></div><span className="tag red">{data.fixture.confidence}% MODEL CONFIDENCE</span></div><div className="disclaimer" data-testid="detail-disclaimer"><ShieldCheck size={17}/><span>{data.notice}</span></div>{data.strategy&&<div className="strategy-banner" data-testid="strategy-banner"><span className="strategy-tag">{data.strategy.format}</span><div><span className="eyebrow">FORMAT STRATEGY</span><b>{data.strategy.profile}</b></div><small>Predictions and multis are calibrated to this format's baseline priors.</small></div>}<div className="detail-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">EVENT PROBABILITIES</span><h2>Model signals</h2></div><span className="mono">ENSEMBLE / V0.8.2</span></div>{data.events.map((e,i)=><div className="signal" data-testid={`prediction-event-${i}`} key={e.market}><div className="signal-main"><span className="signal-num">0{i+1}</span><div><b>{e.selection}</b><small>{e.market} · {e.confidence} confidence</small>{e.drivers&&<div className="drivers">{e.drivers.map(d=><span key={d}>{d}</span>)}</div>}</div></div><div className="prob"><strong>{e.probability}%</strong><div className="bar"><i style={{width:`${e.probability}%`}}/></div></div></div>)}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">SAME-GAME MULTIS</span><h2>Combination engine</h2></div></div>{data.same_game.map((m,i)=><div className="multi" data-testid={`same-game-multi-${i}`} key={m.label}><div><b>{m.label}</b>{m.legs.map(l=><span key={l}>+ {l}</span>)}</div><strong>{m.probability}%<small>JOINT PROB.</small></strong></div>)}</section></div></div></Shell> }
function Portfolio() { const [data,setData]=useState(null); useEffect(()=>{axios.get(`${API}/portfolio/predictions`).then(r=>setData(r.data))},[]); return <Shell><div className="page"><div className="page-intro"><div><div className="eyebrow accent">COMBINATION ENGINE / CROSS-FIXTURE</div><h1>Portfolios</h1><p>Cross-match analytical combinations, ranked by joint probability.</p></div></div><div className="disclaimer" data-testid="portfolio-disclaimer"><ShieldCheck size={17}/><span><b>READ-ONLY ANALYSIS</b> Joint probabilities use a transparent independence approximation.</span></div><div className="portfolio-grid">{data?.portfolios.map((p,i)=><div className="portfolio" data-testid={`portfolio-card-${i}`} key={p.name}><div className="portfolio-top"><span className="eyebrow">PORTFOLIO 0{i+1}</span><span className="tag blue">{p.confidence}</span></div><h2>{p.name}</h2><div className="portfolio-prob"><b>{p.probability}%</b><span>JOINT PROBABILITY</span></div>{p.selections.map(s=><div className="selection" key={s}><span>{s}</span><ChevronRight size={15}/></div>)}</div>)}</div></div></Shell> }
function History() { const [data,setData]=useState(null); useEffect(()=>{axios.get(`${API}/analytics/history`).then(r=>setData(r.data))},[]); return <Shell><div className="page"><div className="page-intro"><div><div className="eyebrow accent">MODEL EVALUATION / HISTORIC</div><h1>Performance</h1><p>Calibration and accuracy from the chronological Cricsheet backtest.</p></div><span className="tag green">● TRACKING HEALTHY</span></div>{data&&<><div className="history-source" data-testid="history-source"><Database size={15}/><span><b>{data.dataset}</b> · Derived from Cricsheet JSON · <a href={data.source} target="_blank" rel="noreferrer" data-testid="history-source-link">SOURCE ARCHIVE ↗</a></span></div><div className="metrics"><Metric label="Accuracy" value={`${data.metrics.accuracy}%`} delta="Chronological baseline" icon={Target}/><Metric label="Brier score" value={data.metrics.brier} delta="Lower is better" icon={Gauge}/><Metric label="Tracked outcomes" value={data.metrics.tracked.toLocaleString()} delta="Real match results" icon={Database}/><Metric label="Calibration" value={`${data.metrics.calibration}%`} delta="Backtest estimate" icon={TrendingUp}/></div><div className="chart-panel"><div className="panel-title"><div><span className="eyebrow">SEASON-BY-SEASON VIEW</span><h2>Accuracy trend</h2></div><span className="mono">ACCURACY %</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><XAxis dataKey="month" stroke="#666"/><YAxis domain={[0,100]} stroke="#666"/><Tooltip contentStyle={{background:"#1b1b1b",border:"1px solid #333"}}/><Area type="monotone" dataKey="accuracy" stroke="#ff3b30" fill="#ff3b30" fillOpacity={.12} strokeWidth={3}/><Area type="monotone" dataKey="calibration" stroke="#34c759" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="table-panel"><div className="panel-title"><div><span className="eyebrow">MARKET BREAKDOWN</span><h2>Tracked performance</h2></div></div><table><thead><tr><th>MARKET</th><th>SAMPLES</th><th>ACCURACY</th><th>BRIER SCORE</th></tr></thead><tbody>{data.markets.map(m=><tr data-testid={`market-row-${m.name.toLowerCase().replace(' ','-')}`} key={m.name}><td>{m.name}</td><td>{m.samples}</td><td className="green-text">{m.accuracy}</td><td>{m.brier}</td></tr>)}</tbody></table></div></>}</div></Shell> }
function Model() { const [data,setData]=useState(null); useEffect(()=>{axios.get(`${API}/analytics/model`).then(r=>setData(r.data))},[]); return <Shell><div className="page"><div className="page-intro"><div><div className="eyebrow accent">MODEL REGISTRY / EXPLAINABILITY</div><h1>Model insight</h1><p>What moves the probability signal, and how the ensemble is versioned.</p></div><span className="tag green">● ACTIVE</span></div>{data&&<><div className="model-banner"><div><span className="eyebrow">CURRENT PRODUCTION CANDIDATE</span><h2>{data.version}</h2></div><div><span className="eyebrow">LAST TRAINED</span><b>{data.trained}</b></div><div><span className="eyebrow">PIPELINE</span><b className="green-text">● COMPLETE</b></div></div><div className="panel feature-panel"><div className="panel-title"><div><span className="eyebrow">FEATURE IMPORTANCE</span><h2>Signal drivers</h2></div><span className="mono">XGBOOST / ENSEMBLE</span></div><div className="feature-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data.features} margin={{left:20,right:30}}><XAxis type="number" stroke="#666"/><YAxis type="category" dataKey="name" width={150} stroke="#aaa"/><Tooltip contentStyle={{background:"#1b1b1b",border:"1px solid #333"}}/><Bar dataKey="importance" fill="#ff3b30" radius={[0,2,2,0]}/></BarChart></ResponsiveContainer></div></div></>}</div></Shell> }
function App(){return <BrowserRouter><Routes><Route path="/" element={<Overview/>}/><Route path="/fixture/:id" element={<Detail/>}/><Route path="/portfolio" element={<Portfolio/>}/><Route path="/history" element={<History/>}/><Route path="/model" element={<Model/>}/></Routes></BrowserRouter>}
export default App;