import { useEffect, useState } from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Layers3, RefreshCw, ShieldCheck, Target } from "lucide-react";
import { useFixtures } from "@/hooks/useFixtures";
import { useFixturePredictions } from "@/hooks/useFixturePredictions";
import Shell from "@/components/layout/Shell";
import MarketsBoard from "@/components/markets/MarketsBoard";
import Overview from "@/pages/Overview";
import FixtureDetail from "@/pages/FixtureDetail";
import "@/App.css";

const fmt = (value) => new Date(value).toLocaleString([], { weekday: "short", hour: "2-digit", minute: "2-digit" });
const getApiErrorMessage = (error, fallback = "Something went wrong. Please try again.") => error?.userMessage || error?.response?.data?.detail || fallback;

function useFixtureMarkets(fixtureId) { const { data } = useFixturePredictions(fixtureId); return data?.markets || []; }
function sgmCorrelationBoost(n) { return n < 2 ? 1 : Math.min(1.25, 1 + 0.05 * (n - 1)); }
function BuildSummary({ legs, label, onReset, onRemove, correlated }) { const raw = legs.length ? legs.reduce((a, l) => a * (l.probability / 100), 1) : 0; const boost = correlated ? sgmCorrelationBoost(legs.length) : 1; const joint = Math.min(0.99, raw * boost); const decimal = joint > 0 ? 1 / joint : 0; const valid = legs.length >= 2; return <div className="build-summary" data-testid="build-summary"><div className="summary-head"><div><span className="eyebrow">{label} · {legs.length} LEG{legs.length === 1 ? "" : "S"}</span><div className="joint-prob" data-testid="joint-probability">{legs.length ? (joint * 100).toFixed(2) : "—"}<i>%</i></div><small>{valid ? (correlated && boost > 1 ? `Correlation-adjusted · +${((boost - 1) * 100).toFixed(0)}% SGM boost` : "Independence approximation") : "Add at least 2 legs to build a multi"}</small></div><div className="summary-payout"><span className="eyebrow">IMPLIED DECIMAL</span><b data-testid="implied-decimal">{decimal ? decimal.toFixed(2) : "—"}</b><small>Analytical payout equivalent</small></div>{!valid && legs.length === 1 && <span className="tag amber" data-testid="need-more-legs">NEED 1 MORE LEG</span>}{legs.length > 0 && <button className="outline-btn" onClick={onReset} data-testid="reset-build"><RefreshCw size={14}/> RESET</button>}</div><div className="legs-list">{legs.length === 0 ? <p className="legs-empty">Tap any selection above to add it as a leg</p> : legs.map((l, i) => <div className="leg-row" data-testid={`leg-${i}`} key={l.key || `${l.fixtureId || "sgm"}-${l.marketKey}-${i}`}><span className="leg-num">0{i + 1}</span><div className="leg-body"><b>{l.selectionName}</b><small>{l.marketLabel}{l.fixtureLabel ? ` · ${l.fixtureLabel}` : ""}</small></div><strong>{l.probability}%</strong><b className="leg-price">@{l.price?.toFixed(2)}</b>{onRemove && <button className="leg-remove" onClick={() => onRemove(l)} data-testid={`remove-leg-${i}`}>×</button>}</div>)}</div></div>; }
function FixturePickChip({ fixture, active, disabled, onClick, testid }) { return <button className={`f-chip ${active ? "active" : ""}`} disabled={disabled} onClick={onClick} data-testid={testid}><small>{fixture.format} · {fixture.competition}</small><b>{fixture.teams[0]} <i>vs</i> {fixture.teams[1]}</b><span>{fmt(fixture.start_time)}</span></button>; }
function SgmBuilder({ fixtures }) { const [fid, setFid] = useState(() => localStorage.getItem("ce.sgm.fid") || ""); const [legs, setLegs] = useState(() => { try { return JSON.parse(localStorage.getItem("ce.sgm.legs")) || []; } catch { return []; } }); const markets = useFixtureMarkets(fid); useEffect(() => { localStorage.setItem("ce.sgm.fid", fid); }, [fid]); useEffect(() => { localStorage.setItem("ce.sgm.legs", JSON.stringify(legs)); }, [legs]); useEffect(() => { if (fid && fixtures.length && !fixtures.find(f => f.id === fid)) { setFid(""); setLegs([]); } }, [fid, fixtures]); const pickFixture = (id) => { if (id !== fid) { setFid(id); setLegs([]); } }; const fixture = fixtures.find(f => f.id === fid); const onSelect = (market, sel) => { setLegs(prev => { const existing = prev.find(l => l.marketKey === market.key); if (existing && existing.key === sel.key) return prev.filter(l => l.key !== sel.key); const filtered = prev.filter(l => l.marketKey !== market.key); return [...filtered, { key: sel.key, marketKey: market.key, marketLabel: market.label, selectionName: sel.name, price: sel.price, probability: sel.probability }]; }); }; const removeLeg = (leg) => setLegs(prev => prev.filter(l => l.key !== leg.key)); const activeKeys = new Set(legs.map(l => l.key)); return <div className="builder"><div className="builder-block"><div className="builder-heading"><span className="eyebrow">1 · PICK ONE FIXTURE</span><small>All SGM legs must come from this match</small></div><div className="fixture-chip-grid" data-testid="sgm-fixture-picker">{fixtures.length === 0 ? <div className="loading">No fixtures available</div> : fixtures.map(f => <FixturePickChip key={f.id} fixture={f} active={fid === f.id} onClick={() => pickFixture(f.id)} testid={`sgm-fixture-${f.id}`}/>)}</div></div>{fid && fixture && <div className="builder-block"><div className="builder-heading"><span className="eyebrow">2 · BUILD YOUR LEGS · {legs.length} SELECTED</span><small>{fixture.teams[0]} vs {fixture.teams[1]} · {markets.length} markets · one selection per market</small></div>{markets.length === 0 ? <div className="loading">Loading markets…</div> : <MarketsBoard markets={markets} activeKeys={activeKeys} onSelect={onSelect}/>}</div>}<BuildSummary legs={legs} label="SAME-GAME MULTI" onReset={() => setLegs([])} onRemove={removeLeg} correlated={true}/></div>; }
function MultibetLegPicker({ fixture, pick, onSelect, idx }) { const markets = useFixtureMarkets(fixture.id); const activeKeys = new Set(pick?.key ? [pick.key] : []); return <div className="leg-picker" data-testid={`multi-leg-picker-${idx}`}><div className="leg-picker-head"><span className="eyebrow">LEG 0{idx + 1} · {fixture.format} · one selection only</span><b>{fixture.teams[0]} <i>vs</i> {fixture.teams[1]}</b></div>{markets.length === 0 ? <div className="loading">Loading…</div> : <MarketsBoard markets={markets} activeKeys={activeKeys} onSelect={(market, sel) => onSelect(fixture.id, market, sel)}/>}</div>; }
function MultibetBuilder({ fixtures }) { const [picks, setPicks] = useState(() => { try { return JSON.parse(localStorage.getItem("ce.multi.picks")) || []; } catch { return []; } }); useEffect(() => { localStorage.setItem("ce.multi.picks", JSON.stringify(picks)); }, [picks]); useEffect(() => { if (fixtures.length) setPicks(prev => prev.filter(p => fixtures.find(f => f.id === p.fixtureId))); }, [fixtures]); const selectedIds = picks.map(p => p.fixtureId); const canAdd = selectedIds.length < 10; const toggleFixture = (fid) => { if (selectedIds.includes(fid)) setPicks(prev => prev.filter(p => p.fixtureId !== fid)); else if (canAdd) setPicks(prev => [...prev, { fixtureId: fid, key: null, marketKey: null, marketLabel: null, selectionName: null, price: null, probability: null }]); }; const onSelect = (fid, market, sel) => setPicks(prev => prev.map(p => { if (p.fixtureId !== fid) return p; if (p.key === sel.key) return { ...p, key: null, marketKey: null, marketLabel: null, selectionName: null, price: null, probability: null }; return { ...p, key: sel.key, marketKey: market.key, marketLabel: market.label, selectionName: sel.name, price: sel.price, probability: sel.probability }; })); const removeLeg = (leg) => setPicks(prev => prev.filter(p => p.key !== leg.key)); const legs = picks.filter(p => p.key != null).map(p => { const f = fixtures.find(fx => fx.id === p.fixtureId); return { ...p, fixtureLabel: f ? `${f.teams[0]} vs ${f.teams[1]}` : "" }; }); return <div className="builder"><div className="builder-block"><div className="builder-heading"><span className="eyebrow">1 · PICK UP TO 10 FIXTURES · {picks.length}/10</span><small>Cross-format allowed · exactly one selection per fixture</small></div><div className="fixture-chip-grid" data-testid="multi-fixture-picker">{fixtures.length === 0 ? <div className="loading">No fixtures available</div> : fixtures.map(f => { const isSelected = selectedIds.includes(f.id); return <FixturePickChip key={f.id} fixture={f} active={isSelected} disabled={!isSelected && !canAdd} onClick={() => toggleFixture(f.id)} testid={`multi-fixture-${f.id}`}/>; })}</div></div>{picks.length > 0 && <div className="builder-block"><div className="builder-heading"><span className="eyebrow">2 · PICK ONE SELECTION PER LEG</span><small>{legs.length}/{picks.length} legs set</small></div><div className="legs-picker-stack">{picks.map((pick, idx) => { const fixture = fixtures.find(f => f.id === pick.fixtureId); return fixture ? <MultibetLegPicker key={pick.fixtureId} fixture={fixture} pick={pick} onSelect={onSelect} idx={idx}/> : null; })}</div></div>}<BuildSummary legs={legs} label="MULTIBET" onReset={() => setPicks([])} onRemove={removeLeg} correlated={false}/></div>; }
function Portfolio() { const [mode, setMode] = useState(() => localStorage.getItem("ce.portfolio.mode") || "SGM"); const { data: fixtures = [], isLoading: loading, error } = useFixtures("ALL"); const switchMode = (m) => { setMode(m); localStorage.setItem("ce.portfolio.mode", m); }; if (error) return <Shell><div className="loading error" data-testid="portfolio-error">{getApiErrorMessage(error, "Unable to load portfolio fixtures.")}</div></Shell>; return <Shell><div className="page"><div className="page-intro"><div><div className="eyebrow accent">COMBINATION ENGINE / INTERACTIVE BUILDER</div><h1>Portfolios</h1><p>Build a same-game multi or a cross-fixture multibet. Joint probability updates live.</p></div></div><div className="disclaimer" data-testid="portfolio-disclaimer"><ShieldCheck size={17}/><span><b>READ-ONLY ANALYSIS</b> Joint probability uses a transparent independence approximation. Not wagering advice.</span></div><div className="mode-tabs" data-testid="portfolio-mode-tabs" role="tablist"><button className={mode === "SGM" ? "active" : ""} onClick={() => switchMode("SGM")} data-testid="mode-sgm"><Layers3 size={14}/> Same-game multi<small>Multiple events · one fixture</small></button><button className={mode === "MULTI" ? "active" : ""} onClick={() => switchMode("MULTI")} data-testid="mode-multi"><Target size={14}/> Multibet<small>One event · up to 10 fixtures</small></button></div>{loading ? <div className="loading" data-testid="portfolio-loading">Loading fixtures…</div> : mode === "SGM" ? <SgmBuilder fixtures={fixtures}/> : <MultibetBuilder fixtures={fixtures}/>}</div></Shell>; }

export default function App() { return <BrowserRouter><Routes><Route path="/" element={<Overview/>}/><Route path="/fixture/:id" element={<FixtureDetail/>}/><Route path="/portfolio" element={<Portfolio/>}/></Routes></BrowserRouter>; }
